import type { PlayerBio, PlayerStats, ScoutRanking, PlayerMeasurements, GameLog, SeasonLog, ScoutingReport } from '../types/player.types.js';
declare class PlayerDataService {
    private data;
    constructor();
    private processData;
    private groupByLeague;
    private groupByNationality;
    private calculateAverageHeight;
    private calculateAverageWeight;
    private calculateAgeDistribution;
    private calculateAge;
    getAllPlayers(): PlayerBio[];
    getAllRankings(): ScoutRanking[];
    getAllMeasurements(): PlayerMeasurements[];
    getAllGameLogs(): GameLog[];
    getAllSeasonLogs(): SeasonLog[];
    getAllScoutingReports(): ScoutingReport[];
    getPlayerById(playerId: number): PlayerBio | undefined;
    getPlayerRankings(playerId: number): ScoutRanking | undefined;
    getPlayerMeasurements(playerId: number): PlayerMeasurements | undefined;
    getPlayerGameLogs(playerId: number): GameLog[];
    getPlayerSeasonLogs(playerId: number): SeasonLog[];
    getPlayerScoutingReports(playerId: number): ScoutingReport[];
    getPlayerStats(): PlayerStats;
    searchPlayers(query: string): PlayerBio[];
    getPlayersByLeague(league: string): PlayerBio[];
    getPlayersByNationality(nationality: string): PlayerBio[];
    getTopRankedPlayers(limit?: number): PlayerBio[];
    private calculateAverageRank;
    getPlayerCompleteProfile(playerId: number): {
        bio: PlayerBio;
        rankings: ScoutRanking | undefined;
        measurements: PlayerMeasurements | undefined;
        gameLogs: GameLog[];
        seasonLogs: SeasonLog[];
        scoutingReports: ScoutingReport[];
    } | undefined;
    getPlayersWithMeasurements(): PlayerBio[];
    getPlayersWithGameLogs(): PlayerBio[];
    getPlayersWithScoutingReports(): PlayerBio[];
}
export declare const playerDataService: PlayerDataService;
export {};
